version: '2'
services:
  server:
    image: 'DOCKERHUB_ID/server:latest'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    links:
      - 'api:api'
  api:
    image: 'DOCKERHUB_ID/api:latest'
    expose:
      - '3000'
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/usr/src/app'
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - NODE_ENV=production
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
    links:
      - message-queue
  message-queue:
    image: 'rabbitmq:management'
    expose:
      - '5672'
    ports:
      - '8080:15672'
  db-worker:
    image: 'DOCKERHUB_ID/db:latest'
    build:
      context: ./db-worker
      dockerfile: Dockerfile
    volumes:
      - './db-worker:/usr/src/app'
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
      - DATABASE_URL=postgres://postgres@db:5432/dev
      - TRANSACTION_DATABASE_URL=postgres://postgres@transactiondb:5432/transactions-dev
    links:
      - message-queue
      - 'db:db'
      - 'transactiondb:transactiondb'
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
  cron:
    image: 'DOCKERHUB_ID/cron:latest'
    build:
      context: ./cron
      dockerfile: Dockerfile
    environment:
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
      - 'DATABASE_URL=postgres://postgres@db:5432/dev'
    links:
      - message-queue
      - 'db:db'
  transactiondb:
    image: 'DOCKERHUB_ID/transactiondb:latest'
    build:
      context: ./
      dockerfile: Dockerfile.transactiondb
    environment:
      - POSTGRES_DB=transactions-dev
      - POSTGRES_USER=postgres
    expose:
      - '5432'
    ports:
      - '5433:5432'
  whichenglish:
    image: 'DOCKERHUB_ID/whichenglish:latest'
    build:
      context: ./workers/whichenglish
      dockerfile: Dockerfile
    volumes:
      - './workers/whichenglish:/usr/src/app'
    command: bash start.debug.sh
    depends_on:
      - message-queue
    environment:
      - 'AMPQ_ADDRESS=amqp://message-queue:5672'
      - QUEUE=whichenglish
    links:
      - message-queue
      